/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-primary-fixed": "#17008c",
        "surface-variant": "#dde3e7",
        "on-surface-variant": "#596063",
        "secondary-fixed": "#e9ddff",
        "error": "#ac3149",
        "surface-bright": "#f7f9fb",
        "secondary": "#6e3bd8",
        "on-secondary-fixed-variant": "#6a37d4",
        "primary-dim": "#4136d6",
        "surface-container-highest": "#dde3e7",
        "tertiary-container": "#61c2ff",
        "tertiary-fixed-dim": "#34b5fa",
        "on-background": "#2d3337",
        "surface-container": "#eaeef1",
        "surface-tint": "#4e45e2",
        "on-tertiary": "#f5f9ff",
        "inverse-on-surface": "#9a9d9f",
        "primary-fixed": "#bdbaff",
        "on-error": "#fff7f7",
        "surface-container-low": "#f1f4f6",
        "error-container": "#f76a80",
        "error-dim": "#770326",
        "primary-fixed-dim": "#adabff",
        "secondary-dim": "#622bcb",
        "inverse-surface": "#0b0f10",
        "outline-variant": "#acb3b7",
        "on-primary": "#fbf7ff",
        "on-primary-fixed-variant": "#3221c9",
        "secondary-container": "#e9ddff",
        "on-secondary-container": "#6029c9",
        "surface-dim": "#d3dbdf",
        "primary-container": "#bdbaff",
        "on-error-container": "#68001f",
        "on-surface": "#2d3337",
        "tertiary-fixed": "#61c2ff",
        "tertiary-dim": "#005980",
        "on-tertiary-fixed": "#002336",
        "surface-container-lowest": "#ffffff",
        "outline": "#757c7f",
        "on-tertiary-fixed-variant": "#004463",
        "on-tertiary-container": "#003b56",
        "surface": "#f7f9fb",
        "on-primary-container": "#280cc1",
        "inverse-primary": "#8582ff",
        "background": "#f7f9fb",
        "on-secondary": "#fdf7ff",
        "on-secondary-fixed": "#4d00b7",
        "secondary-fixed-dim": "#ddcdff",
        "primary": "#4e45e2",
        "tertiary": "#006592",
        "surface-container-high": "#e3e9ec"
      },
      fontFamily: {
        "headline": ["Manrope"],
        "body": ["Inter"],
        "label": ["Inter"]
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "1rem",
        "xl": "1.5rem",
        "full": "9999px"
      },
    },
  },
  plugins: [],
}
