apiVersion: v1
kind: Secret
metadata:
  name: eventix-backend-secret
  namespace: default
type: Opaque
stringData:
  PORT: "5000"
  IMAGEKIT_PUBLIC_KEY: "public_dummy_key_eventix"
  IMAGEKIT_PRIVATE_KEY: "private_dummy_key_eventix"
  IMAGEKIT_URL_ENDPOINT: "https://ik.imagekit.io/eventix"
  RAZORPAY_KEY_ID: "rzp_live_SWGQvXCjLzQsXG"
  RAZORPAY_KEY_SECRET: "dummy_razorpay_secret"
  VITE_EMAILJS_SERVICE_ID: "service_lbpbiva"
  VITE_EMAILJS_TEMPLATE_ID: "template_bv190ih"
  VITE_EMAILJS_PUBLIC_KEY: "WH4a2jO66EFhL3X_c"
